server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://aapbxljtj83by7.cj477qoaxlxp.eu-central-1.rds.amazonaws.com:5432/quickhelper
    username: admin10
    password: admin10Test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true