package com.quickhelper.backoffice.users.enums;

public enum Position {
    ADMIN, MODERATOR,
    CIO, CTO, PO, DIRECTOR, ARCHITECT, CONSULTANT,
    MANAGER, TEACH_LEAD, DATA_SCIENTIST,
    CLIENT_DEVELOPER, SERVER_DEVELOPER, FULLSTACK_DEVELOPER,
    MANUAL_QA, AUTOMATION_QA, BUSINESS_ANALYST,
    UX_DESIGNER, ARTIST_2D, ARTIST_3D, ANIMATOR,
    DEVOPS, CLOUD_SYSTEM_ENGINEER, SECURITY_SPECIALIST,
    DATABASE_ADMINISTRATOR, NETWORK_ENGINEER,
    SYSTEM_ENGINEER, HELP_DESK_TECHNICAL, SUPPORT_SPECIALIST,
    OFFICE_MANAGER, OTHER
}
